### PR TITLE
Fix an infinite loop in some cases in postprocess

### PR DESCRIPTION
**Pull request by DrChat**
Whoops!

### CODE REVIEW

**Comment by Lonami** [comment]
Can you please bump the patch version number in `Cargo.toml` too?

**Comment by DrChat** [comment]
Sure thing! Give me a few and I'll push up a new commit.

**Comment by DrChat** [comment]
Done.

Also, fyi: I have a bunch more changes coming soon after hooking up `cargo-fuzz` to this crate. Most of it is just converting assert statements to `DecodeFailed` errors.

**Comment by Lonami** [comment]
Thanks.

**Pull request merged**
